services:
  postgres:
    image: postgres:16
    container_name: rotas_vl_postgres
    environment:
      POSTGRES_DB: rotas_vl
      POSTGRES_USER: rotas_user
      POSTGRES_PASSWORD: MAMEDE3276
      TZ: America/Sao_Paulo
    volumes:
      - rotas_vl_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: rotas_vl_app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://rotas_user:MAMEDE3276@postgres:5432/rotas_vl
      FLASK_ENV: production
      TZ: America/Sao_Paulo
    ports:
      - "8001:8001"
    command: >
      gunicorn
      --bind 0.0.0.0:8001
      --workers 3
      main:app

volumes:
  rotas_vl_postgres_data: